### ISSUE TITLE
Deploy a serverless PHP web application

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/cake-app-01#1]
# TODO
- [x] Make sure I have my cert set up for douglasnaphas.com (this project will live at a subdomain/subdomains of douglasnaphas.com), in Terraform if not already done (and maybe even if already done)
- [ ] Try to deploy a PHP app with [bref](https://github.com/brefphp/bref).
- [ ] User Lambda layers.
- [ ] Go through the [Terraform API Gateway/Lambda guide](https://learn.hashicorp.com/terraform/aws/lambda-api-gateway).
- [ ] Create an S3 bucket for the code to reside in and other resources to depend on _Might be unnecessary if I use bref_
- [x] Look for Terraform SAM app examples

**Comment by douglasnaphas** [comment]
I might revise this issue to _Deploy a serverless PHP web application_. Using [bref](https://github.com/brefphp/bref), I think I can do that more easily than deploying a Lambda with Terraform, and it's closer to what I want to do (run a Cake app).

**Comment by douglasnaphas** [comment]
I was able to deploy a serverless PHP site to https://1u7idevbm2.execute-api.us-east-1.amazonaws.com/dev, closing.

<img width="799" alt="screenshot of a live site saying 'hello w/ php' at https://1u7idevbm2.execute-api.us-east-1.amazonaws.com/dev" src="https://user-images.githubusercontent.com/5433410/88681536-8a337c80-d0a6-11ea-92ae-90333395769c.png">

**Comment by douglasnaphas** [comment]
# Resources

1. https://learn.hashicorp.com/terraform/aws/lambda-api-gateway
2. https://bref.sh/docs/runtimes/http.html
3. https://bref.sh/docs/local-development.html
4. https://bref.sh/docs/runtimes/index.html
5. https://bref.sh/docs/first-steps.html#initializing-the-project
6. https://bref.sh/docs/runtimes/
7. https://www.serverless.com/blog/definitive-guide-terraform-serverless
8. https://www.php.net/manual/en/tutorial.firstpage.php
